name: Get artifact version
inputs:
  repo_ref:
    type: string
    required: false
    default: ${{github.ref}}
  repo_name:
    type: string
    required: false
    default: ${{github.repository}}
outputs:
  value:
    value: ${{steps.semantic.outputs.changed}}
  projected_release:
    value: ${{steps.semantic.outputs.changed}}

runs:
  using: composite
  steps:
    - name: Show inputs
      shell: bash
      run: |
        echo "repo_name=${{inputs.repo_name}}"
        echo "repo_ref=${{inputs.github_ref}}"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{inputs.repo_name}}
        ref: ${{inputs.repo_ref}}
        fetch-depth: 0

    - name: Get the semantic version values for repo
      id: semantic
      uses: paulhatch/semantic-version@v5.4.0

    - name: Set the output version value
      id: version
      shell: bash
      run: |
        REF=${{inputs.repo_ref}}
        if git show-ref --tags --verify --quiet "refs/tags/${REF}"
        then
          echo "value=${{steps.semantic.outputs.version_tag}}" >> $GITHUB_OUTPUT
        else
          echo "value=${{steps.semantic.outputs.version_tag}}-${REF#refs/heads/}-latest" >> $GITHUB_OUTPUT
        fi
