name: Execute Terraform command
inputs:
  aws_account_id:
    type: string
    required: true
  aws_region:
    type: string
    required: true
  action:
    type: string
    required: false
    default: apply-plan
  environment:
    type: string
    required: true
  tfdir:
    type: string
    required: false
    default: terraform
  checkout_repo:
    type: boolean
    required: false
    default: false
  repo_name:
    type: string
    required: false
    default: ${{ github.repository }}
  repo_ref:
    type: string
    required: false
    default: ${{ github.event.ref }}

runs:
  using: composite
  steps:
    - name: Show inputs
      shell: bash
      run: |
        echo "aws_account_id=${{inputs.aws_account_id}}"
        echo "aws_region=${{inputs.aws_region}}"
        echo "action=${{inputs.action}}"
        echo "environment=${{inputs.environment}}"
        echo "tfdir=${{inputs.tfdir}}"
        echo "checkout_repo=${{inputs.checkout_repo}}"
        echo "repo_name=${{inputs.repo_name}}"
        echo "repo_ref=${{inputs.repo_ref}}"

    - name: Clone the repository
      if: ${{ inputs.checkout_repo }}
      uses: actions/checkout/@v4
      with:
        repository: ${{inputs.repo_name}}
        ref: ${{inputs.repo_ref}}
        sparse-checkout_repo: ${{inputs.tfdir}}

    - name: Configure credentials
      uses: aws-actions/configure-aws-credentials/@v4
      with:
        role-to-assume: arn:aws:iam::${{inputs.aws_account_id}}:role/IaC
        aws-region: ${{inputs.aws_region}}

    - name: Install Terraform on runner
      uses: hashicorp/setup-terraform@v3.1.2

    - name: Extract the unqualified repo name
      id: unqualified_repo_name
      env:
        REPO_NAME: ${{inputs.repo_name}}
      run: |
        echo "value=${REPO_NAME##*/}" >> $GITHUB_OUTPUT

    - name: Terraform init
      shell: bash
      working-directory: ${{inputs.tfdir}}
      run: | 
        terraform init \
          -backend-config="bucket=tf-state-bucket-${{inputs.aws_account_id}}" \
          -backend-config="key=${{inputs.environment}}-${{steps.unqualified_repo_name.outputs.value}}.tfstate" \
          -backend-config="region=${{inputs.aws_region}}" \
          -backend-config="use_lockfile=true" \

    - name: Conditionally set the planning mode to destroy
      if: ${{contains(inputs.action,'destroy')}}
      id: planmode
      shell: bash
      run: echo "value=-destroy" >> $GITHUB_OUTPUT

    - name: Terraform plan (${{inputs.action}})
      working-directory: ${{inputs.tfdir}}
      shell: bash
      run: | 
        terraform plan -input=false ${{steps.planmode.outputs.value}}

    - name: Terraform state change (${{inputs.action}})
      if: ${{!endsWith(inputs.action,'-plan')}}
      working-directory: ${{inputs.tfdir}}
      shell: bash
      run: | 
        terraform apply -auto-approve -input=false ${{steps.planmode.outputs.value}}
      