name: Test artifact-version

on: 
    workflow_dispatch:

jobs:
    greetings:
        name: Execute test
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout sources to make local actions available
              uses: actions/checkout@v4

            - name: Get versions for selected reference
              id: version
              uses: ./actions/artifact-version

            - name: Output results
              run: |
                echo "branch_semantic=${{steps.version.outputs.branch}}"
                echo "release_semantic=${{steps.version.outputs.release}}"
                echo "projected_release=${{steps.version.outputs.projected_release}}"
              